%% Verification Script: fc_mnist
%% Method: relax-star-range (relax_factor=0.5)
%% Auto-generated by generate_scripts.py

% Note: clear/clc removed to allow running from run_all_nnv.m
global baseDir; cd(baseDir);  % Restore working directory

%% Configuration
modelName = 'fc_mnist';
modelPath = 'models/fc_mnist/fc_mnist.onnx';
samplePath = 'samples/fc_mnist_sample.mat';
outputDir = 'outputs/nnv/fc_mnist/relax-star-range_0_50';
outputFile = 'results_relax_star_range_0_50.mat';

epsilon = 0.003921568627451;
numClasses = 10;

reachMethod = 'relax-star-range';
relaxFactor = 0.50;

fprintf('======================================================================\n');
fprintf('Verification: %s\n', modelName);
fprintf('Method: %s (relaxFactor=%.2f)\n', reachMethod, relaxFactor);
fprintf('======================================================================\n\n');

%% Load Network
fprintf('Loading network from: %s\n', modelPath);
netonnx = importONNXNetwork(modelPath, "InputDataFormats", "BCSS", "OutputDataFormats", "BC");
net = matlab2nnv(netonnx);
net.OutputSize = numClasses;
fprintf('Network loaded successfully.\n');

%% Load Test Sample
fprintf('Loading test sample from: %s\n', samplePath);
data = load(samplePath);
img = data.image;
label = data.label;

fprintf('Test sample loaded. Label: %d\n', label);

%% Verification Settings
reachOptions = struct;
reachOptions.reachMethod = reachMethod;
if relaxFactor > 0
    reachOptions.relaxFactor = relaxFactor;
end

fprintf('\nReach options:\n');
fprintf('  Method: %s\n', reachOptions.reachMethod);
if isfield(reachOptions, 'relaxFactor')
    fprintf('  Relax factor: %.2f\n', reachOptions.relaxFactor);
end

%% Create Input Set (L-infinity perturbation)
fprintf('\nCreating input set with epsilon = %.6f\n', epsilon);

lb_min = zeros(size(img));
ub_max = ones(size(img));
lb_clip = max((img - epsilon), lb_min);
ub_clip = min((img + epsilon), ub_max);

% Create ImageStar for ONNX-imported networks (expects image format input)
% Reshape to H x W x C format for ImageStar
% Handle 2D images (H x W) by adding channel dimension
if ndims(img) == 2
    img_hwc = reshape(img, [size(img, 1), size(img, 2), 1]);
    lb_hwc = reshape(lb_clip, [size(lb_clip, 1), size(lb_clip, 2), 1]);
    ub_hwc = reshape(ub_clip, [size(ub_clip, 1), size(ub_clip, 2), 1]);
else
    % Assume C x H x W format, convert to H x W x C
    img_hwc = permute(img, [2, 3, 1]);
    lb_hwc = permute(lb_clip, [2, 3, 1]);
    ub_hwc = permute(ub_clip, [2, 3, 1]);
end

IS = ImageStar(lb_hwc, ub_hwc);
fprintf('ImageStar created. Size: [%s]\n', num2str(size(lb_hwc)));

%% Evaluate Nominal Input
fprintf('\nEvaluating nominal input...\n');

% Use image format for evaluate
output = net.evaluate(img_hwc);
[~, P] = max(output);
P = P - 1;  % Convert to 0-indexed for comparison with Python

fprintf('Nominal prediction: %d\n', P);

%% Run Verification
fprintf('\nRunning verification...\n');
t = tic;

try
    % Compute reachable sets
    R = net.reach(IS, reachOptions);
    verifyTime = toc(t);

    % Get bounds from all output stars
    lb_out = inf(numClasses, 1);
    ub_out = -inf(numClasses, 1);

    for i = 1:length(R)
        [lb_i, ub_i] = R(i).getRanges;
        lb_out = min(lb_out, squeeze(lb_i));
        ub_out = max(ub_out, squeeze(ub_i));
    end

    numOutputSets = length(R);

    % Check robustness
    trueLabel = label + 1;  % MATLAB 1-indexed
    trueClassLB = lb_out(trueLabel);
    isRobust = true;
    for i = 1:numClasses
        if i ~= trueLabel
            if ub_out(i) >= trueClassLB
                isRobust = false;
                break;
            end
        end
    end

    if isRobust
        robust = 1;
    else
        robust = -1;
    end

    success = 1;
    errorMsg = '';

catch ME
    verifyTime = toc(t);
    lb_out = zeros(numClasses, 1);
    ub_out = zeros(numClasses, 1);
    numOutputSets = 0;
    robust = -1;
    success = 0;
    errorMsg = ME.message;
    fprintf('Error during verification: %s\n', ME.message);
end

%% Print Results
fprintf('\n======================================================================\n');
fprintf('RESULTS\n');
fprintf('======================================================================\n');
fprintf('Computation time: %.4f seconds\n', verifyTime);
fprintf('Number of output sets: %d\n', numOutputSets);
fprintf('Robustness: %s\n', ternary(robust == 1, 'ROBUST', 'NOT ROBUST'));

fprintf('\nOutput bounds:\n');
fprintf('%-8s %-20s %-20s %-15s\n', 'Class', 'Lower Bound', 'Upper Bound', 'Width');
fprintf('%s\n', repmat('-', 1, 65));
for i = 1:numClasses
    width = ub_out(i) - lb_out(i);
    marker = '';
    if i == label + 1
        marker = ' <-- TRUE';
    end
    fprintf('%-8d %-20.10f %-20.10f %-15.10f%s\n', i-1, lb_out(i), ub_out(i), width, marker);
end
fprintf('======================================================================\n');

%% Save Results
fprintf('\nSaving results to: %s\n', fullfile(outputDir, outputFile));

% Create output directory if it doesn't exist
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

expResults = struct();
expResults.experiment_id = 7;
expResults.model = modelName;
expResults.method = reachMethod;
expResults.set_type = 'star';
expResults.epsilon = epsilon;
expResults.relax_factor = relaxFactor;
expResults.test_label = label;
expResults.nominal_output = output;
expResults.nominal_pred = P;
expResults.output_lb = lb_out;
expResults.output_ub = ub_out;
expResults.num_output_sets = numOutputSets;
expResults.computation_time = verifyTime;
expResults.robust = robust;
expResults.success = success;
if ~isempty(errorMsg)
    expResults.error = errorMsg;
end

save(fullfile(outputDir, outputFile), 'expResults');
fprintf('Results saved successfully.\n');

%% Helper function
function out = ternary(cond, a, b)
    if cond
        out = a;
    else
        out = b;
    end
end
