%% Verification Script: toy_fc_8_4_2 (Toy Model)
%% Method: approx
%% Set Type: zono
%% Auto-generated by generate_scripts.py

% Note: clear/clc removed to allow running from run_all_nnv.m
global baseDir; cd(baseDir);  % Restore working directory

%% Configuration
modelName = 'toy_fc_8_4_2';
modelPath = 'models/toy_fc_8_4_2/toy_fc_8_4_2.onnx';
samplePath = 'samples/toy_fc_8_4_2_sample.mat';
outputDir = 'outputs/nnv/toy_fc_8_4_2/zono';
outputFile = 'results_zono.mat';

epsilon = 0.100000000000000;
numClasses = 2;
setType = 'zono';

reachMethod = 'approx-star';

fprintf('======================================================================\n');
fprintf('Verification: %s (Toy)\n', modelName);
fprintf('Method: %s, Set Type: %s\n', reachMethod, setType);
fprintf('======================================================================\n\n');

%% Load Network
fprintf('Loading network from: %s\n', modelPath);
netonnx = importONNXNetwork(modelPath, "InputDataFormats", "BC", "OutputDataFormats", "BC");
net = matlab2nnv(netonnx);
net.OutputSize = numClasses;
fprintf('Network loaded successfully.\n');

%% Load Test Sample
fprintf('Loading test sample from: %s\n', samplePath);
data = load(samplePath);
input = data.input(:);  % Ensure column vector
inputDim = length(input);

fprintf('Test sample loaded. Input dimension: %d\n', inputDim);

%% Create Input Set
fprintf('\nCreating %s input set with epsilon = %.6f\n', setType, epsilon);

lb = input - epsilon;
ub = input + epsilon;

if strcmp(setType, 'zono')
    % Create Zonotope
    c = (lb + ub) / 2;
    V = diag((ub - lb) / 2);
    IS = Zono(c, V);
    fprintf('Zono created.\n');
elseif strcmp(setType, 'box')
    % Create Box (as Star with box constraints)
    IS = Star(lb, ub);
    fprintf('Box (Star) created.\n');
else
    error('Unknown set type: %s', setType);
end

%% Evaluate Nominal Input
fprintf('\nEvaluating nominal input...\n');

output = net.evaluate(input);
[~, P] = max(output);
P = P - 1;  % Convert to 0-indexed

fprintf('Nominal output: %s\n', mat2str(output', 4));
fprintf('Nominal prediction: %d\n', P);

%% Run Verification
fprintf('\nRunning verification...\n');
t = tic;

try
    % Compute reachable sets
    reachOptions = struct;
    reachOptions.reachMethod = reachMethod;

    R = net.reach(IS, reachOptions);
    verifyTime = toc(t);

    % Get bounds from all output sets
    lb_out = inf(numClasses, 1);
    ub_out = -inf(numClasses, 1);

    for i = 1:length(R)
        if isa(R(i), 'Zono')
            [lb_i, ub_i] = R(i).getBounds;
        else
            [lb_i, ub_i] = R(i).getRanges;
        end
        lb_out = min(lb_out, squeeze(lb_i));
        ub_out = max(ub_out, squeeze(ub_i));
    end

    numOutputSets = length(R);
    success = 1;
    errorMsg = '';

catch ME
    verifyTime = toc(t);
    lb_out = zeros(numClasses, 1);
    ub_out = zeros(numClasses, 1);
    numOutputSets = 0;
    success = 0;
    errorMsg = ME.message;
    fprintf('Error during verification: %s\n', ME.message);
end

%% Print Results
fprintf('\n======================================================================\n');
fprintf('RESULTS\n');
fprintf('======================================================================\n');
fprintf('Computation time: %.4f seconds\n', verifyTime);
fprintf('Number of output sets: %d\n', numOutputSets);

fprintf('\nOutput bounds:\n');
fprintf('%-8s %-20s %-20s %-15s\n', 'Output', 'Lower Bound', 'Upper Bound', 'Width');
fprintf('%s\n', repmat('-', 1, 65));
for i = 1:numClasses
    width = ub_out(i) - lb_out(i);
    fprintf('%-8d %-20.10f %-20.10f %-15.10f\n', i-1, lb_out(i), ub_out(i), width);
end
fprintf('======================================================================\n');

%% Save Results
fprintf('\nSaving results to: %s\n', fullfile(outputDir, outputFile));

% Create output directory if it doesn't exist
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

expResults = struct();
expResults.experiment_id = 37;
expResults.model = modelName;
expResults.method = reachMethod;
expResults.set_type = setType;
expResults.epsilon = epsilon;
expResults.relax_factor = 0;
expResults.test_label = 0;  % N/A for toy models
expResults.nominal_output = output;
expResults.nominal_pred = P;
expResults.output_lb = lb_out;
expResults.output_ub = ub_out;
expResults.num_output_sets = numOutputSets;
expResults.computation_time = verifyTime;
expResults.robust = 1;  % N/A for toy models
expResults.success = success;
if ~isempty(errorMsg)
    expResults.error = errorMsg;
end

save(fullfile(outputDir, outputFile), 'expResults');
fprintf('Results saved successfully.\n');
